spring.application.name=helloworld

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
spring.security.user.name=admin
spring.security.user.password=1234
server.port=${PORT:8080}