spring.application.name=helloworld

spring.datasource.url=postgresql://postgres:gqhwpDkTIeKYLnkevizzcpCSFBFnYcXB@acela.proxy.rlwy.net:19235/railway
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


telegram.bot.token=8690079592:AAHQ2Qtf61pF6mhKvsllbCbDk2jr6naD2Ds
spring.security.user.name=admin
spring.security.user.password=1234
server.port=${PORT:8080}