spring.application.name=helloworld

spring.datasource.url=${DATABASE_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false
spring.datasource.hikari.connection-init-sql=SET statement_timeout = '30s'
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
spring.datasource.hikari.data-source-properties.prepareThreshold=0

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
spring.security.user.name=admin
spring.security.user.password=1234
server.port=${PORT:8080}